apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bW9uZ291c2Vy     # required field for kubernetes.io/basic-auth
  password: bW9uZ29wYXNzd29yZA== # required field for kubernetes.io/basic-auth